apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-ui-dep
spec:
  selector:
    matchLabels:
      app: sample-ui
  replicas: 10
  template:
    metadata:
      labels:
        app: sample-ui
    spec:
      containers:
        - name: sample-ui-ctr
          image: cepster/sampleui:latest
          ports:
            - containerPort: 80
